server:
  port: 8002
spring:
  application:
    name: service-oss


aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: you
      keysecret: you
      bucketname: allweing-guli